services:
  aithreatdetection:
    container_name: aithreatdetcionservice
    build:
      context: .
      dockerfile: ../Dockerfile
    environment:
      - DATABASE_URL=postgresql://csadmin:cssecurepassword@cshybrid-postgres:5432/cshybrid_db

      - OPENSEARCH_URL=http://cshybrid-opensearch:9200
    networks:
      - cshybrid-network
    depends_on:
      - cshybrid-postgres
      - cshybrid-opensearch
    entrypoint:
      - sh
      - -c
      - ./wait-for-services.sh cshybrid-postgres 5432 && ./wait-for-services.sh cshybrid-opensearch 9200 && python main.py
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  cshybrid-postgres:
    image: postgres:15
    container_name: cshybrid-postgres
    environment:
      - POSTGRES_USER=csadmin
      - POSTGRES_PASSWORD=cssecurepassword
      - POSTGRES_DB=cshybrid_db

    ports:
      - "5432:5432"
    networks:
      - cshybrid-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "csadmin"]
      interval: 30s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - cshybrid_postgres_data:/var/lib/postgresql/data

  cshybrid-opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: cshybrid-opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx1g  # Increased memory
    networks:
      - cshybrid-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 30s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 2G  # Increased memory limit
        reservations:
          memory: 1G  # Increased memory reservation
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - cshybrid_opensearch_data:/usr/share/opensearch/data

networks:
  cshybrid-network:
    driver: bridge

volumes:
  cshybrid_postgres_data:
  cshybrid_opensearch_data:
